main: com.edtheloon.gold2economy.gold2economy
name: Gold2Economy
author: EdTheLoon
description: Convert your iron, gold and diamonds to money in either iConomy or BOSEconomy
version: 1.4
softdepend: [Register]

commands:
    gi:
        description: Turn your iron, gold or diamonds into money.
        usage: |
            /gi - Shows this help menu
            /gi rates - Shows you the conversion rates
            /gi <item> <amount> - Where <amount> is the amount of <item> to convert. <item> can be iron, gold or diamond
            /gi <item> all - Converts all your gold ingots into money. <item> can be iron, gold or diamond
            /gi reload - Reload config (Admin command)
permissions:
    Gold2Economy.*:
        description: Gives access to all Gold2Economy features
        children:
            Gold2Economy.admin: true
            Gold2Economy.iron: true
            Gold2Economy.gold: true
            Gold2Economy.diamond: true
    Gold2Economy.iron:
        description: Allow users to convert iron
        default: true
    Gold2Economy.gold:
        description: Allow users to convert gold
        default: true
    Gold2Economy.diamond:
        description: Allow users to convert diamond
        default: true
    Gold2Economy.admin:
        description: Allow users to use admin commands/features
        default: op