# Gold2Economy - Vault Configuration
# "convert" - true/false, convert <ITEM>
# "rates" - double (decimal), rate for <ITEM>
# "permissions":
#    "use" - true/false, use permissions
#    "Permissions" - true/false, use Permissions Nijikokun
#    "PermissionBukkit" - true/false, use default Bukkit permission system
convert:
	iron: false
	gold: true
	diamond: false
rates:
	iron:
	gold:
	diamond:
permissions:
	use: true
	Permissions: false
	PermissionsBukkit: true
preferred: iConomy 6
